### PR TITLE
fix(#4143): error to session ux

### LINKED ISSUE #4143: Polish the error to session flow
When opening a session from the error page, 

- open the popover over the corresponding bar
- change the popover to show the error body rather than the secure id
- open the errors tab in dev tools

### PR DESCRIPTION
**Pull request by aptlin**
## Summary

Resolves #4143:
open the popover over the corresponding bar
change the popover to show the error body rather than the secure id
open the errors tab in dev tools

## How did you test this change?

local click test
## Are there any deployment considerations?

no

### CODE REVIEW

File: frontend/src/pages/Error/components/ErrorComments/ErrorComments.tsx [hunk 1]
```diff
@@ -111,7 +111,6 @@ const ErrorCommentHeader = ({ comment, children, errorGroup }: any) => {
 	const { isIntegrated: isClickupIntegrated } = useIsProjectIntegratedWith(
 		IntegrationType.ClickUp,
 	)
-	debugger
```
Comment (Vadman97) [inline frontend/src/pages/Error/components/ErrorComments/ErrorComments.tsx:114]: lol good catch

**Review by Vadman97 — APPROVED** [review]
nice!
