### PR TITLE
fix:group by options duplication issue is fixed

### LINKED ISSUE #8580: dashboard group by options show duplicates

### PR DESCRIPTION
**Pull request by rajeshj11**
## Summary
/claim #8580 
/fixes #8580 

Group by options duplications were handled in the graph editor session

## How did you test this change?
https://www.loom.com/share/c9c9b2e8be2745f898ec9d48cb61da01

### CODE REVIEW

**Comment by rajeshj11** [comment]
@Vadman97 could you please review this PR?

File: frontend/src/pages/Graphing/GraphingEditor.tsx [hunk 1]
```diff
@@ -619,16 +624,30 @@ export const GraphingEditor = () => {
...
+	function getUniqueKeys(data: QueryKeyTypes[]): QueryKeyTypes[] {
+		return Object.values(
+			data.reduce((obj, key: QueryKeyTypes) => {
+				if (!obj[key.name]) {
+					obj[key.name] = key
+				}
+				return obj
+			}, {} as { [key: QueryKeyTypes['name']]: QueryKeyTypes }),
+		) as QueryKeyTypes[]
+	}
```
Comment (Vadman97) [inline frontend/src/pages/Graphing/GraphingEditor.tsx:637]: could also be rewritten using the `lodash` library using
https://www.geeksforgeeks.org/lodash-_-keys-method/ and https://www.geeksforgeeks.org/lodash-_-uniq-method/

**Review by Vadman97 — APPROVED** [review]
reflame preview looks good!

File: frontend/src/pages/Graphing/GraphingEditor.tsx (hunk 1 above)
Comment (rajeshj11) [reply frontend/src/pages/Graphing/GraphingEditor.tsx:637]: @Vadman97 yeah sure, it is a simple change. are there any other changes needed from my side

**Comment by rajeshj11** [comment]
@Vadman97 handled the feedback changes. please review

**Review by Vadman97 — APPROVED** [review]
nice!

**Comment by rajeshj11** [comment]
@Vadman97 some checks have failed it seems.
Screenshot from 2024-06-11 11-43-11

**Comment by rajeshj11** [comment]
> @Vadman97 some checks have failed it seems. Screenshot from 2024-06-11 11-43-11

@Vadman97 ^^ are there any changes required from my side

**Comment by rajeshj11** [comment]
@Vadman97 could please take a look at this when  you are free

**Comment by rajeshj11** [comment]
> @Vadman97 could you please take a look at this when you are free

@Vadman97 ^^ could you please check this
