### PR TITLE
fix length filter, skip cache for sessions/errors query/histogram

### LINKED ISSUE #6647: session feed results cached
See the error page on Highlight:
https://app.highlight.io/1/sessions/AnBd8R3ZHfF08JoY2bDEtwqfKvwl

### PR DESCRIPTION
**Pull request by mayberryzane**
## Summary
- length filter should be multiplied by 1000, max value should be treated as infinity
- parse as float because "advanced mode" passes in float values
- fetch results and histogram using 'network-only' to skip cache
- fixes #6647 

## How did you test this change?
- click tested locally

## Are there any deployment considerations?
- no

## Does this work require review from our design team?
- no

### CODE REVIEW

File: backend/clickhouse/querybuilder.go [hunk 1]
```diff
@@ -228,14 +229,19 @@ func parseColumnRule(admin *model.Admin, rule Rule, projectId int, sb *sqlbuilde
...
 				return "", err
 			}
-			end, err := strconv.ParseInt(after, 10, 64)
+			start *= 1000
+			end, err := strconv.ParseFloat(after, 64)
 			if err != nil {
 				return "", err
 			}
+			end *= 1000
+			if after == "60" {
```
Comment (Vadman97) [inline backend/clickhouse/querybuilder.go:242]: what's this hard-coded condition for?

**Review by Vadman97 — APPROVED** [review]
thanks for the quick fixes!

File: backend/clickhouse/querybuilder.go (hunk 1 above)
Comment (mayberryzane) [reply backend/clickhouse/querybuilder.go:243]: added comment - this condition exists for opensearch, if the slider is all the way to the right (at 60 mins) we should allow any greater length as well
