### PR TITLE
#4415 Fix network request filtering

### LINKED ISSUE #4415: Network request types don't properly filter network data.

### PR DESCRIPTION
**Pull request by aaronmaxcarver**
## Summary

- Resolves #4415, "Network request types don't properly filter network data." 

- Updated RequestType enum values to match received request types

## How did you test this change?

- Just dev mode click test

Screenshot 2023-03-04 at 3 45 57 AM

Screenshot 2023-03-04 at 3 46 05 AM

## Are there any deployment considerations?

-none

### CODE REVIEW

File: frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts [hunk 1]
```diff
@@ -118,37 +125,32 @@ export const LogLevelVariants = {
...
-	Events = 'Events',
+	Link = 'link',
+	Script = 'script',
+	Other = 'other',
+	XHR = 'xmlhttprequest',
+	CSS = 'css', 
+	iFrame = 'iframe', // didn't find a request to verify that 'iframe' is what is actually received
+	Fetch = 'fetch',
+	Img = 'img',
 }
```
Comment (Vadman97) [inline frontend/src/pages/Player/Toolbar/DevToolsWindowV2/utils.ts:137]: looks like lint fails on this file - you can run `yarn format:all` in the repo to lint everything.

image

**Review by Vadman97 — APPROVED** [review]
looks great 🎉  just needs a lint
