### PR TITLE
fix(#3925): clean up the live mode for sessions

### LINKED ISSUE #3925: Changes to live session experience.
Make some changes to live sessions:
1) Linking to a live session should put you into "non-live" mode by default
2) Change the copy of the button from "Live" to "Switch to live mode"
3) Julianify the live loading modal

Customer feedback / background.
"- it took me a few minutes to figure out clicking on "Live" takes you to the session navigator view for live sessions"

How can we make the the Live indicator more obvious? For some reason it doesn't obviously look like a button, it just looks like an indicator. 

cc @vadim

### PR DESCRIPTION
**Pull request by aptlin**
## Summary

Resolves #3925:

Linking to a live session should put you into "non-live" mode by default
Change the copy of the button from "Live" to "Switch to live mode"
Julianify the live loading modal

## How did you test this change?

Local click test

## Are there any deployment considerations?

no

### CODE REVIEW

File: frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx [hunk 1]
```diff
@@ -419,7 +419,6 @@ const ResourceRow = ({
 						className={styles.timingBar}
 						style={{
 							width: `${actualPercent}%`,
-							zIndex: 100,
```
Comment (aptlin) [inline frontend/src/pages/Player/Toolbar/DevToolsWindowV2/NetworkPage/NetworkPage.tsx:422]: To avoid this:
Screenshot 2023-02-07 at 9 08 05 AM

**Comment by jay-khatri** [comment]
two comments:
- on live sessions, in the timeline, i'm often in a position where I get this sorta error (`NaN`). Is this because the session is too short?
image

- can we make this button primary in both the live and non-live state? 
image

- I could be wrong, but is the text in that ^ button vertically ccentered?

**Review by Vadman97 — APPROVED** [review]
nice!
