### PR TITLE
fix(#4124): network panel ui & ux

### LINKED ISSUE #4124: 500 requests aren't represented as erroneous
With the new network UI, are we representing 500 requests as red/erroneous? If not, do we need a design? cc @julian-highlight for any support.

Image

### PR DESCRIPTION
**Pull request by aptlin**
## Summary

Resolves #4124.

Removes the deprecated DetailPanel as well. 

## How did you test this change?

local click test

## Are there any deployment considerations?

no

### CODE REVIEW

File: frontend/src/pages/Player/context/PlayerUIContext.ts [hunk 1]
```diff
@@ -30,10 +30,6 @@ interface PlayerUIContext {
 	setIsPlayerFullscreen: React.Dispatch<React.SetStateAction<boolean>>
 	playerCenterPanelRef: React.RefObject<HTMLDivElement>
 	/** Used to show detailed information. */
-	detailedPanel?: DetailedPanel
-	setDetailedPanel: React.Dispatch<
```
Comment (ccschmitz) [inline frontend/src/pages/Player/context/PlayerUIContext.ts:34]: Can the `DetailedPanel` and `DetailedPanelOptions` interfaces be cleaned up now as well?

**Review by ccschmitz — APPROVED** [review]
Code + click test look great! One quick question about another potential clean up.
