### PR TITLE
Next.js SDK import and build cleanup

### LINKED ISSUE #6741: [Nodejs/Nextjs] Cannot find module BatchSpanProcessorBase
Greetings!

Wanted to use highlight-run/node, but it doesn't work.

I'm using nextjs, but I don't need the full integration - just to catch few console.logs on the backend.

So I just installed @highlight-run/node, and:

```js
import { H } from '@highlight-run/node';

H.init({ projectID: '***' });

...
console.log('my stuff');
```

Getting the error :
```
error - Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/node_modules/@opentelemetry/sdk-trace-base/build/src/export/BatchSpanProcessorBase' imported from /t/node_modules/@highlight-run/node/dist/index.mjs
Did you mean to import @opentelemetry/sdk-trace-base/build/src/export/BatchSpanProcessorBase.js?
    at new NodeError (node:internal/errors:387:5)
    at finalizeResolution (node:internal/modules/esm/resolve:330:11)
    at moduleResolve (node:internal/modules/esm/resolve:907:10)
    at defaultResolve (node:internal/modules/esm/resolve:1115:11)
    at nextResolve (node:internal/modules/esm/loader:163:28)
    at ESMLoader.resolve (node:internal/modules/esm/loader:841:30)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:424:18)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:76:40)
    at link (node:internal/modules/esm/module_job:75:36) {
  code: 'ERR_MODULE_NOT_FOUND'
}

```

What am I doing wrong?

**To Reproduce**
1. npm install --save @highlight-run/node ("@highlight-run/node": "3.4.0",)
2. import { H } from '@highlight-run/node';
3. H.init({ projectID: '***' });
4. Getting the error

### PR DESCRIPTION
**Pull request by deltaepsilon**
The console is clean. The errors are flowing.

image

I'm still working on Page Router SSR errors. I think I'll need a different approach to get them reliable. I'll also be able to drop `instrumentation.ts`.

closes #6741

### CODE REVIEW

**Comment by deltaepsilon** [comment]
Closes #6716 6716

File: e2e/nextjs/pages/_error.tsx [hunk 1]
```diff
@@ -0,0 +1,20 @@
+// pages/_error.tsx
+import NextError from 'next/error'
```
Comment (deltaepsilon) [inline e2e/nextjs/pages/_error.tsx:2]: This new `pages/_error.tsx` file reports Page Router SSR errors from the client. It's more reliable than attempting to send them from the server.

File: sdk/highlight-cloudflare/package.json [hunk 2]
```diff
@@ -1,13 +1,13 @@
...
-	"version": "2.1.0",
+	"version": "2.1.1",
 	"packageManager": "yarn@3.2.3",
 	"main": "./dist/index.js",
 	"module": "./dist/index.mjs",
 	"types": "./dist/index.d.ts",
 	"scripts": {
 		"dev": "yarn build --watch",
-		"build": "tsup src/index.ts --format cjs,esm --dts",
+		"build": "tsup",
```
Comment (deltaepsilon) [inline sdk/highlight-cloudflare/package.json:10]: I moved these options to a `tsup.config.ts` file.

File: sdk/highlight-next/src/next-client.tsx [hunk 3]
```diff
@@ -29,3 +32,16 @@ export function HighlightInit({
 
 	return null
 }
+
+export type HighlightErrorProps = { errorMessage: string } & ErrorProps
```
Comment (deltaepsilon) [inline sdk/highlight-next/src/next-client.tsx:36]: Export `getHighlightErrorInitialProps` to streamline `pages/_error.tsx` creation.

File: sdk/highlight-node/tsup.config.ts [hunk 4]
```diff
@@ -0,0 +1,18 @@
+import { defineConfig } from 'tsup'
+
+export default defineConfig({
+	entry: ['src/index.ts'],
+	format: ['cjs', 'esm'],
+	dts: true,
+	sourcemap: true,
+	noExternal: [
```
Comment (deltaepsilon) [inline sdk/highlight-node/tsup.config.ts:8]: Bundle all of `@opentelemetry/*`

File: sdk/highlight-cloudflare/package.json [hunk 5]
```diff
@@ -24,11 +24,11 @@
 		"hoistingLimits": "workspaces"
 	},
 	"dependencies": {
+		"@highlight-run/opentelemetry-sdk-workers": "workspace:*",
```
[the remark this answers is not in the document]
Comment (Vadman97) [reply sdk/highlight-cloudflare/package.json:27]: does this mean we need to publish the `@highlight-run/opentelemetry-sdk-workers` npm package? should we do that as part of this PR?

File: sdk/highlight-next/bin/clean-dist.sh [hunk 6]
```diff
@@ -1,2 +1,5 @@
-printf '%s%s' '"use client";' "$(cat dist/next-client.js)" > dist/next-client.js
-printf '%s%s' '"use client";' "$(cat dist/next-client.cjs)" > dist/next-client.cjs
+sed -i '/"use client";/d' dist/next-client.js
```
[the remark this answers is not in the document]
Comment (Vadman97) [reply sdk/highlight-next/bin/clean-dist.sh:1]: yeah, this doesn't work
```
 ✘  ~/w/h/s/highlight-next   vadim/filters   sed -i '/"use client";/d' dist/next-client.js
sed: 1: "dist/next-client.js": extra characters at the end of d command
```

any other alternatives to sed? otherwise you can make the command work on both mac and non-mac if we get the sed syntax right. now sure how tho

File: sdk/highlight-next/package.json [hunk 7]
```diff
@@ -46,16 +46,16 @@
 		"react": ">=17"
 	},
 	"dependencies": {
+		"@highlight-run/cloudflare": "workspace:^",
```
Comment (Vadman97) [inline sdk/highlight-next/package.json:49]: can we make this `workspace:*`?

**Review by Vadman97 — APPROVED** [review]
can we make sure to fix #6741 as part of this? do we need to patch `@opentelemetry/sdk-trace-base` to export `BatchSpanProcessorBase`? or otherwise, could we copy over the base implementation to avoid the import?

File: sdk/highlight-node/tsup.config.ts (hunk 4 above)
Comment (Vadman97) [reply sdk/highlight-node/tsup.config.ts:8]: interesting :D this might allow getting https://github.com/open-telemetry/opentelemetry-js/commit/5615b1c1857606e2ba5e591c924eb45448dbcb61 sooner by allowing us to change the version to our fork

Comment (Vadman97) [reply sdk/highlight-node/tsup.config.ts:8]: good to know that's what `noExternal` does!

File: sdk/highlight-next/package.json (hunk 7 above)
Comment (deltaepsilon) [reply sdk/highlight-next/package.json:49]: Yessir! Thanks for the reminder.

File: sdk/highlight-next/bin/clean-dist.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (deltaepsilon) [reply sdk/highlight-next/bin/clean-dist.sh:1]: I'm going to try this fix:
https://stackoverflow.com/questions/26081375/bsd-sed-extra-characters-at-the-end-of-d-command

File: sdk/highlight-cloudflare/package.json (hunk 5 above)
[the remark this answers is not in the document]
Comment (deltaepsilon) [reply sdk/highlight-cloudflare/package.json:27]: Ugh. Of course! Thanks for catching this. Yes... I'll figure this out.

**Comment by deltaepsilon** [comment]
> can we make sure to fix #6741 as part of this? do we need to patch `@opentelemetry/sdk-trace-base` to export `BatchSpanProcessorBase`? or otherwise, could we copy over the base implementation to avoid the import?

I believe that this line solves it:
https://github.com/highlight/highlight/pull/6712/files#diff-dae3ed183dead92d218bea1221cbdf501c7135437f67affc1c2c84c17ad0099bR15

Here's a screenshot of the bundled file that makes me feel more confident:
image

I'll still need to test this in a separate project once this lands.
