### PR TITLE
fix(#4234): session feed settings

### LINKED ISSUE #4234: [session ui] Fix the session settings menu
Update the design of the menu and make sure that it's easy to close it (at the moment only clicking on the trigger button makes it disappear)

Screenshot 2023-02-13 at 8 38 06 AM

### PR DESCRIPTION
**Pull request by aptlin**
## Summary

Resolves #4234.

was:
Screenshot 2023-02-15 at 1 48 18 PM

now:
Screenshot 2023-02-15 at 1 48 02 PM

## How did you test this change?

local click test

go to the session feed settings in the top left

## Are there any deployment considerations?

no

### CODE REVIEW

File: frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.tsx [hunk 1]
```diff
@@ -40,51 +41,84 @@ export const DropdownMenu = function ({
...
+
+	const [delayClose, setDelayClose] = useState(false)
+
+	useWindowEvent('click', (event) => {
+		if (
+			!(
+				isInsideElement(event, menuRef.current) ||
+				isInsideElement(event, buttonRef.current)
+			) &&
+			!delayClose
```
Comment (aptlin) [inline frontend/src/pages/Sessions/SessionsFeedV3/SessionQueryBuilder/components/SessionFeedConfigurationV2/SessionFeedConfigurationV2.tsx:57]: A bit hacky, but using ref for submenus did not work (because the element was destroyed by the time the listener fires)

**Review by Vadman97 — APPROVED** [review]
