### PR TITLE
Fix deep linking to session search

### LINKED ISSUE #4098: "Top Users" deep link doesn't work.
"When I click one of our top users in the dashboard, I'm sent to a list of everyone's completed sessions – not their's."

### PR DESCRIPTION
**Pull request by ccschmitz**
## Summary

Deep linking to sessions with query parameters is broken in a number of places. This PR updates many of these links to stop passing any parameters besides `query` and adds some helpers for building a `query` string param that can be used in the URL and `searchParams`.

There is also some refactoring and consolidation of logic in various `useEffect`s for query builder components. This fixed a bug with URL state not being preserved on deep links and (hopefully) makes the logic a little easier to follow.

Resolves #4098, #4095, #4120

## How did you test this change?

Local click test.

## Are there any deployment considerations?

Want to make sure all existing behavior remains in tact and that we didn't introduce any issues with the consolidation of the logic in various `useEffect`s.

### CODE REVIEW

File: frontend/src/pages/Home/components/ActiveUsersTable/ActiveUsersTable.tsx [hunk 1]
```diff
@@ -100,20 +100,16 @@ const ActiveUsersTable = ({
...
-									value: record.identifier,
-								},
-							],
+
+						const userParam = validateEmail(record.identifier)
+							? 'email'
+							: 'identifier'
+						history.push({
+							pathname: `/${projectIdRemapped}/sessions`,
+							search: `?query=and%7C%7Cuser_${userParam}%2Cis%2C${record.identifier}`,
```
Comment (ccschmitz) [inline frontend/src/pages/Home/components/ActiveUsersTable/ActiveUsersTable.tsx:110]: Might be something in session query builder that can generate this string.

Comment (ccschmitz) [reply frontend/src/pages/Home/components/ActiveUsersTable/ActiveUsersTable.tsx:110]: Use email address when available instead of `record.identifier`.
