### PR TITLE
fix nil pointer references and remove noisy frontend errors

### LINKED ISSUE #5556: runtime error: invalid memory address or nil pointer dereference
workspace can be undefined

See the error page on Highlight:
https://app.highlight.io/1/errors/MSQYy41pUCXpJREijV0zfWRmkAFv
```[tasklist]
### Tasks
- [ ] subscription details workspace
```

### LINKED ISSUE #5590: error getting linear teams: linear graphql API responded with error; status_code=400 Bad Request; body={"errors":[{"message":"Authentication required, not authenticated","extensions":{"code":"AUTHENTICATION_ERROR","type":"authentication error","userError":true,"userPresentableMessage":"You need to authenticate to access this operation.","meta":{}}}]}
api returns error when the integration is not configured

See the error page on Highlight:
https://app.highlight.io/1/errors/ms7U1pwOsBoyV9SWmpnYIoHrtIQI

### PR DESCRIPTION
**Pull request by Vadman97**
## Summary

Fixes resolver logic that's causing nil pointers in our frontend.
Removes noisy frontend errors that are reported from the preload code.

Closes #5556
Closes #5590

## How did you test this change?

New unit tests.
Testing the relevant graphql operations locally.

## Are there any deployment considerations?

No

### CODE REVIEW

File: frontend/src/util/preload.ts [hunk 1]
```diff
@@ -312,9 +312,7 @@ export const loadSession = async function (secureID: string) {
 			},
 		])
 	} catch (e: any) {
-		const msg = `failed to preload session ${secureID}`
```
Comment (et) [inline frontend/src/util/preload.ts:315]: Is there something else going on here? Like why are we trying to load a session that doesn't exist (or isn't available at the time)?

File: backend/private-graph/graph/schema.resolvers.go [hunk 2]
```diff
@@ -6323,7 +6323,7 @@ func (r *queryResolver) GithubIssueLabels(ctx context.Context, workspaceID int,
 func (r *queryResolver) Project(ctx context.Context, id int) (*model.Project, error) {
 	project, err := r.isAdminInProjectOrDemoProject(ctx, id)
 	if err != nil {
-		return nil, nil
+		return nil, err
```
Comment (et) [inline backend/private-graph/graph/schema.resolvers.go:6326]: Wonder if we can write a lint rule for this 🤔

**Review by et — APPROVED** [review]
Thanks for cleaning up the noise 🥇 
While looking through some [lint rule configs](https://golangci-lint.run/usage/linters/#errcheck), I did file #5593 for fixing another issue with our error handling.
If you get a moment, check out that page when you have a chance to see if there's anything else you think would help out here.

File: backend/private-graph/graph/resolver.go [hunk 3]
```diff
@@ -474,9 +474,6 @@ func (r *Resolver) isAdminInProject(ctx context.Context, project_id int) (*model
 
 	span.SetTag("ProjectID", project_id)
 
-	if util.IsTestEnv() {
-		return nil, nil
-	}
```
Comment (Vadman97) [inline backend/private-graph/graph/resolver.go:479]: this was to bypass the auth context, but i'm changing the tests to leverage the simple auth mode instead and not need this mock.

File: frontend/src/util/preload.ts (hunk 1 above)
Comment (Vadman97) [reply frontend/src/util/preload.ts:315]: the session is available, but it might not have timeline indicators / network resources, so some of the other graphql calls here may fail.
