### PR TITLE
fix log alert delete

### LINKED ISSUE #6620: error trying to delete log alert: WHERE conditions required
real user error deleting log alert

See the error page on Highlight:
https://app.highlight.io/1/errors/AiwbzitH8kw1po5IdfEbLPlHBeXC

### PR DESCRIPTION
**Pull request by mayberryzane**
## Summary
- query was selecting an arbitrary alert in the project rather than by id
- refetching `GetLogAlert` after deletion was returning an error as the alert doesn't exist anymore
- fixes #6620 

## How did you test this change?
- click tested locally

## Are there any deployment considerations?
- no

## Does this work require review from our design team?
- no

### CODE REVIEW

File: backend/private-graph/graph/schema.resolvers.go [hunk 1]
```diff
@@ -3063,13 +3063,14 @@ func (r *mutationResolver) DeleteLogAlert(ctx context.Context, projectID int, id
 	}
 
 	alert := &model.LogAlert{}
-	if err := r.DB.Model(&model.LogAlert{Model: model.Model{ID: id}}).
```
Comment (Vadman97) [inline backend/private-graph/graph/schema.resolvers.go:3066]: wonder if it's possible to set up a lint rule for non-zero-value structs passed to `.Model()` as that seems like always misguided

**Review by Vadman97 — APPROVED** [review]
