### PR TITLE
fix node sdk timeouts

### LINKED ISSUE #6987: @highlight-run/node times out exporting data
**Describe the bug**
```
error: "highlight-node failed to flush:  Error [OTLPExporterError]: Request Timeout" 
```

Screenshot 2023-10-27 at 2 04 23 PM

### PR DESCRIPTION
**Pull request by Vadman97**
## Summary

Our node SDK was throwing red-herring errors while shipping logs / traces because of
the interval flush logic. This logic was not needed as OTEL has it's own loop for flushing data.

* fixes recursion error during stringification of certain objects #6839 
* ensures console attributes are correctly reported correctly as structured attributes
* ensures we fully rely on bundling opentelemetry to help with #7010

Closes #6987

## How did you test this change?

tested locally by ingesting a network latency `tc qdisc add dev lo root netem delay 10000ms`

before
Screenshot from 2023-10-31 14-25-11

after
Screenshot from 2023-10-31 14-29-55

Logs coming through correctly locally

Screenshot from 2023-10-31 16-03-25

tested in next js edge runtime as well

## Are there any deployment considerations?

No

## Does this work require review from our design team?

Changeset

### CODE REVIEW

File: sdk/highlight-node/src/hooks.ts [hunk 1]
```diff
@@ -33,18 +36,22 @@ interface ConsolePayload {
...
 }
 
 type ConsoleFn = (...data: any) => void
 
 let consoleHooked = false
 
 export function safeStringify(obj: any): string {
-	function replacer(input: any): any {
+	function replacer(input: any, depth?: number): any {
+		if ((depth ?? 0) > MAX_RECURSION) {
```
Comment (SpennyNDaJets) [inline sdk/highlight-node/src/hooks.ts:48]: Curious the impact if something where to be over the `MAX_RECURSION` value? The value seems low to the minimum browser results.

**Review by SpennyNDaJets — APPROVED** [review]
Code looks good!

File: sdk/highlight-node/src/hooks.ts (hunk 1 above)
Comment (Vadman97) [reply sdk/highlight-node/src/hooks.ts:48]: I think it's unlikely an object someone wants to serialize intentionally will be deeper than 128 children, while keeping the value low means it's faster to detect a cycle in the object.
