### PR TITLE
fix(#4094): stop duplicating segments

### LINKED ISSUE #4094: Renaming a segment duplicates it
From discord: https://discord.com/channels/1026884757667188757/1052834249868324895/1068966294851956736

### PR DESCRIPTION
**Pull request by aptlin**
## Summary

Starts checking if a segment with the same name exists on create/update for errors and sessions.

Closes #4094.
## How did you test this change?

Local click test. The preview will not work because of the backend changes.

## Are there any deployment considerations?

no

### CODE REVIEW

File: backend/private-graph/graph/schema.resolvers.go [hunk 1]
```diff
@@ -2,6 +2,7 @@ package graph
 
 // This file will be automatically regenerated based on the schema, any resolver implementations
 // will be copied through when generating and any unknown code will be moved to the end.
+// Code generated by github.com/99designs/gqlgen version v0.17.24
```
Comment (Vadman97) [inline backend/private-graph/graph/schema.resolvers.go:5]: why this comment? this is making github hide the diff, and this file isn't generated

Comment (aptlin) [reply backend/private-graph/graph/schema.resolvers.go:5]: This was autogenerated by make private-gen

File: backend/public-graph/graph/schema.resolvers.go [hunk 2]
```diff
@@ -2,6 +2,7 @@ package graph
 
 // This file will be automatically regenerated based on the schema, any resolver implementations
 // will be copied through when generating and any unknown code will be moved to the end.
+// Code generated by github.com/99designs/gqlgen version v0.17.24
```
[the remark this answers is not in the document]
Comment (aptlin) [reply backend/public-graph/graph/schema.resolvers.go:5]: Autogenerated by make public-gen

File: backend/private-graph/graph/schema.resolvers.go (hunk 1 above)
Comment (Vadman97) [reply backend/private-graph/graph/schema.resolvers.go:5]: hmm but now the files are hidden in the diff tab. could we have this not generate or otherwise tell github to show the diffs?

Screenshot 2023-02-06 at 1 40 44 PM

Comment (Vadman97) [reply backend/private-graph/graph/schema.resolvers.go:5]: hmm... looks like this is happening in main anyways without this change.

**Review by Vadman97 — APPROVED** [review]
